#!/bin/bash -e

ROOT=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd "$ROOT"

while IFS= read file; do
  ./tgt2/out/x86_64-macos/gvasm runtest "$file"
done < <(find tests -type f -name '*.txt' | sort)
